data:
  target: dataset.data_module.BIRDataModule
  params:
    # Path to training set configuration file.
    train_config: ./configs/dataset/face_train.yaml
    # Path to validation set configuration file.
    val_config: ./configs/dataset/face_val.yaml

model:
  # You can set learning rate in the following configuration file.
  config: configs/model/cldm.yaml
  # Path to the checkpoints or weights you want to resume. At the begining, 
  # this should be set to the initial weights created by scripts/make_stage2_init_weight.py.
  resume: ./weights/checkpoints/FlowIE_bfr_v1.ckpt

lightning:
  seed: 231
  
  trainer:
    #GPU info
    accelerator: ddp
    precision: 16 #32
    # Indices of GPUs used for training.
    gpus: [0]

    # accelerator: gpu
    # precision: 16-mixed #32
    # devices: 1
    # strategy: ddp

    # Path to save logs and checkpoints.
    default_root_dir: ./work_dirs/exp1

    # Max number of training steps (batches).
    # max_steps: 250001                                 #TODO CHECK
    max_steps: 200

    # Validation frequency in terms of training steps.
    # val_check_interval: 500
    # log_every_n_steps: 50
    limit_val_batches: 0.0

    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
    gradient_clip_val: 1.0
  
  callbacks:
    - target: model.callbacks.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 250
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: model.callbacks.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 3000
        save_top_k: -1
        filename: "{step}"
